# Generated by Django 4.1 on 2022-08-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_alter_anime_options_review_reviewtype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
