# Generated by Django 4.1 on 2022-08-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message'),
        ('animes', '0005_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CurrentEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField(blank=True, default=0, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='currentEpisodes',
            field=models.ManyToManyField(blank=True, to='animes.currentepisode'),
        ),
    ]
