# Generated by Django 4.1 on 2022-08-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0006_anime_anime_length_currentepisode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='currentEpisodes',
        ),
        migrations.AddField(
            model_name='review',
            name='currentEpisode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='anime_length',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
