# Generated by Django 4.1 on 2022-08-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0007_remove_anime_currentepisodes_review_currentepisode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='currentEpisode',
        ),
        migrations.AlterField(
            model_name='anime',
            name='anime_length',
            field=models.IntegerField(blank=True, default=9999, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200),
        ),
    ]
