# Generated by Django 4.1 on 2022-08-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0008_remove_review_currentepisode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='currentEpisodes',
            field=models.ManyToManyField(blank=True, to='animes.currentepisode'),
        ),
    ]
