# Generated by Django 4.1 on 2022-08-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0009_anime_currentepisodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='currentEpisodes',
        ),
        migrations.DeleteModel(
            name='CurrentEpisode',
        ),
    ]
